# Generated by Django 2.2.28 on 2022-09-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cashcalls", "0001_initial"),
        ("bill", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalbill",
            name="cashcall",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="cashcalls.CashCall",
                verbose_name="CashCall",
            ),
        ),
        migrations.AddField(
            model_name="historicalbill",
            name="history_relation",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="history",
                to="bill.Bill",
            ),
        ),
    ]
