# Generated by Django 2.2.28 on 2022-09-12 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cashcalls", "0002_historicalcashcall_history_user"),
        ("bill", "0004_historicalbill_investment"),
        ("investor", "0001_initial"),
        ("core_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalbill",
            name="investor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="investor.Investor",
                verbose_name="Investor",
            ),
        ),
        migrations.AddField(
            model_name="historicalbill",
            name="platform_relation",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core_management.PlatformRelation",
                verbose_name="Platform relation",
            ),
        ),
        migrations.AddField(
            model_name="historicalbill",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="cashcall",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bills",
                to="cashcalls.CashCall",
                verbose_name="CashCall",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="investment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bills",
                to="core_management.Investment",
                verbose_name="Investment",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="investor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bills",
                to="investor.Investor",
                verbose_name="Investor",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="platform_relation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core_management.PlatformRelation",
                verbose_name="Platform relation",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bills_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
    ]
