# Generated by Django 2.2.28 on 2022-09-14 10:13

import django_fsm
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0005_auto_20220912_1451"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="acceleration_percentage",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="historicalbill",
            name="acceleration_percentage",
        ),
        migrations.RemoveField(
            model_name="historicalbill",
            name="amount",
        ),
        migrations.AddField(
            model_name="bill",
            name="amount_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="Amount due",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="cc_emails",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="fees_amount_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="Fees Amount Due",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="sendinblue_template_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("CREATED", "created"),
                    ("PAID", "paid"),
                    ("PAID_INCORRECTLY", "paid_incorrectly"),
                    ("PENDING", "pending"),
                    ("FAILED", "failed"),
                ],
                default="created",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="historicalbill",
            name="amount_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="Amount due",
            ),
        ),
        migrations.AddField(
            model_name="historicalbill",
            name="cc_emails",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalbill",
            name="fees_amount_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=19,
                null=True,
                verbose_name="Fees Amount Due",
            ),
        ),
        migrations.AddField(
            model_name="historicalbill",
            name="sendinblue_template_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="historicalbill",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("CREATED", "created"),
                    ("PAID", "paid"),
                    ("PAID_INCORRECTLY", "paid_incorrectly"),
                    ("PENDING", "pending"),
                    ("FAILED", "failed"),
                ],
                default="created",
                max_length=50,
            ),
        ),
    ]
