# Generated by Django 2.2.28 on 2022-09-23 10:00

from decimal import Decimal

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0006_auto_20220914_1213"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="amount_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=19,
                null=True,
                verbose_name="Amount due",
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="fees_amount_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=19,
                null=True,
                verbose_name="Fees Amount Due",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbill",
            name="amount_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=19,
                null=True,
                verbose_name="Amount due",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbill",
            name="fees_amount_due",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=19,
                null=True,
                verbose_name="Fees Amount Due",
            ),
        ),
    ]
