# Generated by Django 2.2.28 on 2022-10-06 12:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0007_auto_20220923_1200"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="investor_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalbill",
            name="investor_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
