# Generated by Django 2.2.28 on 2022-10-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0008_auto_20221006_1439"),
        ("cashcalls", "0006_manual_move_payin_to_cashcall"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="cashcall",
        ),
        migrations.RemoveField(
            model_name="historicalbill",
            name="cashcall",
        ),
    ]
