# Generated by Django 2.2.28 on 2023-01-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_auto_20221227_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='year',
            field=models.IntegerField(blank=True, choices=[(2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2023, null=True, verbose_name='Issuing year'),
        ),
        migrations.AlterField(
            model_name='historicalbill',
            name='year',
            field=models.IntegerField(blank=True, choices=[(2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2023, null=True, verbose_name='Issuing year'),
        ),
    ]
