# Generated by Django 2.2.28 on 2023-01-09 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0011_auto_20230102_2100"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="bill",
                    name="investment",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bills",
                        to="investment.Investment",
                        verbose_name="Investment",
                    ),
                ),
                migrations.AlterField(
                    model_name="historicalbill",
                    name="investment",
                    field=models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="investment.Investment",
                        verbose_name="Investment",
                    ),
                ),
            ],
            database_operations=[],
        )
    ]
