# Generated by Django 2.2.28 on 2022-09-12 12:51

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CashCall",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "investor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fees_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "committed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                (
                    "total_committed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                (
                    "total_fees_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                ("cc_emails", models.TextField(blank=True, null=True)),
                ("sendinblue_template_id", models.IntegerField(null=True)),
                (
                    "last_sent",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last sent"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalCashCall",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "investor_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fees_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "committed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                (
                    "total_committed_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                (
                    "total_fees_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=19, null=True
                    ),
                ),
                ("cc_emails", models.TextField(blank=True, null=True)),
                ("sendinblue_template_id", models.IntegerField(null=True)),
                (
                    "last_sent",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last sent"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_relation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="history",
                        to="cashcalls.CashCall",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cash call",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
