# Generated by Django 2.2.28 on 2022-09-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cashcalls", "0002_historicalcashcall_history_user"),
        ("investor", "0001_initial"),
        ("core_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalcashcall",
            name="investor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="investor.Investor",
                verbose_name="investor.Investor",
            ),
        ),
        migrations.AddField(
            model_name="historicalcashcall",
            name="payin",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core_management.PayIn",
                verbose_name="PayIn",
            ),
        ),
        migrations.AddField(
            model_name="cashcall",
            name="investor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_calls",
                to="investor.Investor",
                verbose_name="investor.Investor",
            ),
        ),
        migrations.AddField(
            model_name="cashcall",
            name="payin",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_call",
                to="core_management.PayIn",
                verbose_name="PayIn",
            ),
        ),
    ]
