# Generated by Django 2.2.28 on 2022-09-14 10:13

import django.db.models.deletion
import django_fsm
import jsonfield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0006_auto_20220914_1213"),
        ("cashcalls", "0003_auto_20220912_1451"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cashcall",
            old_name="total_fees_amount",
            new_name="fees_amount",
        ),
        migrations.RenameField(
            model_name="historicalcashcall",
            old_name="total_fees_amount",
            new_name="fees_amount",
        ),
        migrations.AddField(
            model_name="cashcall",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cashcalls",
                to="bill.Bill",
            ),
        ),
        migrations.AddField(
            model_name="cashcall",
            name="mangopay_payin_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="cashcall",
            name="response",
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="cashcall",
            name="status",
            field=django_fsm.FSMField(default="created", max_length=50),
        ),
        migrations.AddField(
            model_name="historicalcashcall",
            name="bill",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="bill.Bill",
            ),
        ),
        migrations.AddField(
            model_name="historicalcashcall",
            name="mangopay_payin_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcashcall",
            name="response",
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="historicalcashcall",
            name="status",
            field=django_fsm.FSMField(default="created", max_length=50),
        ),
    ]
