# Generated by Django 2.2.28 on 2022-09-23 10:00

from decimal import Decimal

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("cashcalls", "0004_auto_20220914_1213"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashcall",
            name="committed_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cashcall",
            name="fees_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcashcall",
            name="committed_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcashcall",
            name="fees_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=19,
                null=True,
            ),
        ),
    ]
